[package]
name = "blooemu"
version = "0.1.4"
edition = "2021"
description = "the best library for OS API's manipulation"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "tlhelp32", "handleapi"] }
notify-rust = "4.5"
cfg-if = "1.0"