[package]
name = "blooemu"
version = "0.1.1"
edition = "2021"
description = "the best library for OS API's manipulation"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
notify-rust = "4.5"